export function buildAppControllerReturn<T extends Record<"acousticFingerprintResult" | "activePage" | "advancedTrackSearch" | "albums" | "appContextMenu" | "applyClapStatus" | "applyFolderWatchResponse" | "applyFolderWatchStatus" | "artistInfo" | "artists" | "artistTracks" | "audioAnalysisCoverage" | "audioAnalysisEligibleTrackTotal" | "audioAnalysisJobId" | "audioAnalysisLimit" | "audioAnalysisOnlyMissing" | "audioAnalysisOverwrite" | "audioAnalysisProgress" | "audioConversionInstallProgress" | "audioConversionJobId" | "audioConversionPreview" | "audioConversionProgress" | "audioConversionRequest" | "audioConversionSetup" | "autoDjAvoidRules" | "autoPlayOnTrackChange" | "autoTagPreview" | "autoWriteFetchedLyricsSidecars" | "backendCheckedAt" | "backendLog" | "backendMessage" | "backendStatus" | "beginLibraryLoad" | "buildDesktopScanSnapshot" | "bulkUndoBatches" | "bulkUndoLog" | "bulkUndoRestoreResult" | "cdAutoLookupMetadata" | "cdDriveDetected" | "cdPlaybackPrepareChainRef" | "cdPlaybackPrepareRequestIdRef" | "cdRipSetup" | "checkBackendStatus" | "chromaprintSetup" | "clapBatchSize" | "clapCacheDir" | "clapInstallProgress" | "clapSamplesPerTrack" | "clapModelId" | "clapNeedsOptionalInstall" | "clapStatus" | "clapStatusLoadMessage" | "clapStatusLoadPercent" | "clearFrontendLocalData" | "coffeeAnimating" | "commitPlayTrack" | "commitTrackIndexCache" | "confirmDeleteTracks" | "continuousAutoDjBusy" | "continuousAutoDjEnabled" | "continuousAutoDjInFlightRef" | "continuousAutoDjSettings" | "currentCdPlaybackDriveId" | "currentLibraryTrackQueryKey" | "currentRadioStation" | "currentTrack" | "debouncedAdvancedTrackSearch" | "debouncedSearch" | "deletePrompt" | "detailTrack" | "deviceSyncPreview" | "dismissQuickStart" | "duplicateActionResult" | "duplicateReview" | "endLibraryLoad" | "ensureLatestCdPlaybackRequest" | "extendContinuousAutoDj" | "externalTrackRequest" | "externalTrackRequestIdRef" | "fileManagementFocusToolId" | "fileManagementScopeIds" | "filenameTagPreview" | "fileOrganizationPreview" | "fileOrganizationReport" | "findTracksByIds" | "folderPath" | "FolderWatchRefreshTimerRef" | "folderWatchStatus" | "handleAcknowledgeFolderWatchNotifications" | "handleAcoustIdApiKeyChange" | "handleAddToQueue" | "handleAddTracksToPlaylist" | "handleAdvancedTagLibraryChanged" | "handleAnalyzeAudio" | "handleAnalyzeTracks" | "handleApplyAutoTag" | "handleApplyFilenameTags" | "handleApplyFileOrganization" | "handleApplyFolderWatch" | "handleApplyMetadataCsv" | "handleApplyTagRegex" | "handleAutoWriteFetchedLyricsSidecars" | "handleAvoidAutoDj" | "handleBackupDatabase" | "handleBrowseAudioConversionTarget" | "handleBrowseCdRipTarget" | "handleBrowseFolder" | "handleBulkMetadata" | "handleBulkRating" | "handleCancelAudioAnalysis" | "handleCancelAudioConversion" | "handleCdAutoLookupMetadata" | "handleChooseMusicFolderAndScan" | "handleClearArtistCache" | "handleClearIgnoredDuplicateGroups" | "handleClearLibraryCaches" | "handleClearPlaybackQueue" | "handleCoffeeClick" | "handleCommitExternalTrackRequest" | "handleContinuousAutoDjChange" | "handleCopySupportBundlePath" | "handleCreatePlaylist" | "handleCreateSupportBundle" | "handleCycleTheme" | "handleDeleteAutoDjAvoidRule" | "handleDeleteInboxAutoReviewRule" | "handleDeletePlaylist" | "handleDeleteRecommendationProfile" | "handleDeleteTrack" | "handleDeleteTracks" | "handleDeviceSync" | "handleDuplicateAction" | "handleExportFileOrganizationReport" | "handleExportMetadataCsv" | "handleExportMetadataCsvReport" | "handleExportPlaylist" | "handleExportTracks" | "handleFetchLyrics" | "handleIgnoreDuplicateGroup" | "handleImportPlaylist" | "handleInstallAudioConversionFfmpeg" | "handleInstallClap" | "handleLastFmApiCredentialsChange" | "handleLibraryAutoTagTracks" | "handleLibraryClapGenreTagTracks" | "handleLibraryFingerprintTagTracks" | "handleLibraryVolumeTagTracks" | "handleLoadDuplicateReview" | "handleMovePlaybackQueueTrack" | "handleMovePlaylistTrack" | "handleOpenBackendLog" | "handleOpenCurrentAlbumFromPlayer" | "handleOpenCurrentArtistFromPlayer" | "handleOpenCurrentTrackFromPlayer" | "handleOpenDetachedMiniPlayer" | "handleOpenExternalUrl" | "handleOpenFileManagementForTracks" | "handleOpenLyricsViewFromPlayer" | "handleOpenOptionalDependencies" | "handleOpenQueueViewFromPlayer" | "handleOpenSourceFolder" | "handlePauseAudioAnalysis" | "handlePlayAlbum" | "handlePlayArtist" | "handlePlayCdPreviewTrack" | "handlePlayNext" | "handlePlayRadioStation" | "handlePlayTrack" | "handlePreviewAudioConversion" | "handlePreviewAutoTag" | "handlePreviewFilenameTags" | "handlePreviewFileOrganization" | "handlePreviewMetadataCsv" | "handlePreviewTagRegex" | "handleQuickAutoDj" | "handleRating" | "handleReadReportFile" | "handleRefreshFolderWatch" | "handleRemoveLibrarySource" | "handleRemovePlaybackQueueTrack" | "handleRemoveTrackFromPlaylist" | "handleRemoveTracksFromPlaylist" | "handleReorderPlaybackQueueTrack" | "handleResetLocalData" | "handleRestartBackend" | "handleRestoreBulkUndoBatch" | "handleRestoreBulkUndoEntry" | "handleRestorePlaybackQueue" | "handleResumeAudioAnalysis" | "handleRevealTrack" | "handleRevealTracksByIds" | "handleReviewInboxTracks" | "handleRunAcousticFingerprintPass" | "handleSaveAudioConversionSetup" | "handleSaveArtistInfoOverride" | "handleSaveChromaprintSetup" | "handleSaveClapConfig" | "handleSaveInboxAutoReviewRule" | "handleSaveLyrics" | "handleSavePlaybackQueue" | "handleSaveRecommendationProfile" | "handleSaveTrackMetadata" | "handleScan" | "handleSelectAlbum" | "handleSelectArtist" | "handleSelectPlaylist" | "handleSetDefaultRecommendationProfile" | "handleShuffleTracks" | "handleStartAudioConversion" | "handleStartFolderWatch" | "handleStopFolderWatch" | "handleStopRadioStation" | "handleSyncFileMetadata" | "handleTrackEnded" | "handleTrackSkipped" | "handleUndoAction" | "handleUndoRecentChange" | "handleUpdateInboxNote" | "handleUseSuggestedFolder" | "handleWriteRatingsToFiles" | "hasAdvancedLibraryFilters" | "hasAnalysisIssue" | "hasLoadedInitialLibrary" | "hasMoreTracks" | "hideFilePaths" | "historyEvents" | "historyStats" | "importPlaylistPath" | "inbox" | "isArtistLoading" | "isAudioAnalyzing" | "isCdPlaybackActive" | "isClapInstalling" | "isClapStatusLoading" | "isLibraryLoading" | "isLyricsLoading" | "isScanning" | "lastFolderWatchNotificationIdRef" | "lastSessionRestoreAttemptedRef" | "lastSessionRestoreFinishedRef" | "lastSessionWriteKeyRef" | "libraryAlbumScrollTop" | "libraryArtistScrollTop" | "libraryCacheQueryKeyRef" | "libraryCompletionScrollTop" | "libraryFolders" | "libraryHealth" | "libraryLoadingCountRef" | "libraryPageRequestsInFlightRef" | "libraryPlaylistScrollTop" | "libraryRequestId" | "libraryScrollTop" | "librarySort" | "libraryStats" | "libraryTotal" | "libraryView" | "libraryVisibleColumns" | "loadAlbums" | "loadAnalysisClapReadiness" | "loadArtistInfo" | "loadArtists" | "loadAudioConversionSetup" | "loadAutoDjAvoidRules" | "loadBulkUndoLog" | "loadCdRipSetup" | "loadChromaprintSetup" | "loadClapCoverage" | "loadClapStatus" | "loadFolderWatchStatus" | "loadHistory" | "loadInbox" | "loadLibraryStats" | "loadMoreTracks" | "loadPlaylists" | "loadPriorityLibraryTracks" | "loadRecommendationHistory" | "loadRecommendationProfiles" | "loadSettings" | "loadStartupDiagnostics" | "loadTracksPage" | "loadTrackWindow" | "lyrics" | "mergeTrackPage" | "metadataCsvExport" | "metadataCsvImportPreview" | "metadataCsvImportReport" | "metadataEditInitialField" | "metadataEditTrack" | "newPlaylistName" | "openApiKeysSettings" | "openAppContextMenu" | "openMetadataEditor" | "playbackMode" | "playbackQueue" | "playbackTime" | "playlists" | "priorityLibraryLoadStartedRef" | "priorityLibraryQueryKeyRef" | "queue" | "queueHistory" | "queueUpcomingPlaybackTracks" | "quickStartDismissed" | "radioPlaybackRequestId" | "recommendationDrift" | "recommendationHistory" | "recommendationProfiles" | "recordTrackExitQuiet" | "recycleFilesWithDesktop" | "refreshAnalyzedState" | "refreshCdPreviewTrack" | "refreshTracks" | "rememberQueueSnapshot" | "rememberRecommendationFeedback" | "removeTrackEverywhere" | "replaceTrackEverywhere" | "replaceUpcomingPlaybackQueue" | "reportFile" | "requestDeleteTracks" | "resolveTracksForAction" | "restoredPlaybackPosition" | "restoreLastPlaybackSession" | "scanProgress" | "scanResult" | "scheduleFolderWatchRefresh" | "search" | "selectedAlbumId" | "selectedAlbumTracks" | "selectedArtistName" | "selectedArtistTracks" | "selectedPlaylistId" | "selectedPlaylistTracks" | "setAcousticFingerprintResult" | "setActivePage" | "setAdvancedTrackSearch" | "setAlbums" | "setAppContextMenu" | "setArtistInfo" | "setArtists" | "setArtistTracks" | "setAudioAnalysisCoverage" | "setAudioAnalysisEligibleTrackTotal" | "setAudioAnalysisJobId" | "setAudioAnalysisLimit" | "setAudioAnalysisOnlyMissing" | "setAudioAnalysisOverwrite" | "setAudioAnalysisProgress" | "setAudioConversionInstallProgress" | "setAudioConversionJobId" | "setAudioConversionPreview" | "setAudioConversionProgress" | "setAudioConversionSetup" | "setAutoDjAvoidRules" | "setAutoPlayOnTrackChange" | "setAutoTagPreview" | "setAutoWriteFetchedLyricsSidecars" | "setBackendCheckedAt" | "setBackendLog" | "setBackendMessage" | "setBackendStatus" | "setBulkUndoBatches" | "setBulkUndoLog" | "setBulkUndoRestoreResult" | "setCdAutoLookupMetadata" | "setCdRipSetup" | "setChromaprintSetup" | "setClapBatchSize" | "setClapCacheDir" | "setClapInstallProgress" | "setClapSamplesPerTrack" | "setClapModelId" | "setClapStatus" | "setClapStatusLoadMessage" | "setClapStatusLoadPercent" | "setCoffeeAnimating" | "setContinuousAutoDjBusy" | "setContinuousAutoDjEnabled" | "setContinuousAutoDjSettings" | "setCurrentRadioStation" | "setCurrentTrack" | "setDebouncedAdvancedTrackSearch" | "setDebouncedSearch" | "setDeletePrompt" | "setDetailTrack" | "setDeviceSyncPreview" | "setDuplicateActionResult" | "setDuplicateReview" | "setExternalTrackRequest" | "setFileManagementFocusToolId" | "setFileManagementScopeIds" | "setFilenameTagPreview" | "setFileOrganizationPreview" | "setFileOrganizationReport" | "setFolderPath" | "setFolderWatchStatus" | "setHasLoadedInitialLibrary" | "setHasMoreTracks" | "setHideFilePaths" | "setHistoryEvents" | "setHistoryStats" | "setImportPlaylistPath" | "setInbox" | "setIsArtistLoading" | "setIsAudioAnalyzing" | "setIsClapInstalling" | "setIsClapStatusLoading" | "setIsLibraryLoading" | "setIsLyricsLoading" | "setIsScanning" | "setLibraryAlbumScrollTop" | "setLibraryArtistScrollTop" | "setLibraryCompletionScrollTop" | "setLibraryFolders" | "setLibraryHealth" | "setLibraryPlaylistScrollTop" | "setLibraryScrollTop" | "setLibrarySort" | "setLibraryStats" | "setLibraryTotal" | "setLibraryView" | "setLibraryVisibleColumns" | "setLyrics" | "setMetadataCsvExport" | "setMetadataCsvImportPreview" | "setMetadataCsvImportReport" | "setMetadataEditInitialField" | "setMetadataEditTrack" | "setNewPlaylistName" | "setPlaybackMode" | "setPlaybackQueue" | "setPlaybackTime" | "setPlaylists" | "setQueue" | "setQueueHistory" | "setQuickStartDismissed" | "setRadioPlaybackRequestId" | "setRecommendationDrift" | "setRecommendationHistory" | "setRecommendationProfiles" | "setReportFile" | "setRestoredPlaybackPosition" | "setScanProgress" | "setScanResult" | "setSearch" | "setSelectedAlbumId" | "setSelectedAlbumTracks" | "setSelectedArtistName" | "setSelectedArtistTracks" | "setSelectedPlaylistId" | "setSelectedPlaylistTracks" | "setSettings" | "setSettingsFocusSection" | "setStartupDiagnostics" | "setStatus" | "setSupportBundlePath" | "setTagRegexPreview" | "setTargetPlaylistId" | "settings" | "settingsFocusSection" | "setTrackIndexCache" | "setTracks" | "setUiPreferences" | "setUndoAction" | "setWriteRatingsToFiles" | "showCdPage" | "showUndoAction" | "startupBackgroundHydratedRef" | "startupDiagnostics" | "startupLibrarySnapshot" | "status" | "supportBundlePath" | "tagRegexPreview" | "targetPlaylistId" | "trackIndexCache" | "trackIndexCacheRef" | "tracks" | "uiPreferences" | "undoAction" | "undoTimerRef" | "updateCachedTracks" | "validateMusicFoldersWithDesktop" | "waitForBackendStartup" | "writeRatingsToFiles", any>>(model: T): {
  acousticFingerprintResult: T["acousticFingerprintResult"];
  activePage: T["activePage"];
  advancedTrackSearch: T["advancedTrackSearch"];
  albums: T["albums"];
  appContextMenu: T["appContextMenu"];
  applyClapStatus: T["applyClapStatus"];
  applyFolderWatchResponse: T["applyFolderWatchResponse"];
  applyFolderWatchStatus: T["applyFolderWatchStatus"];
  artistInfo: T["artistInfo"];
  artists: T["artists"];
  artistTracks: T["artistTracks"];
  audioAnalysisCoverage: T["audioAnalysisCoverage"];
  audioAnalysisEligibleTrackTotal: T["audioAnalysisEligibleTrackTotal"];
  audioAnalysisJobId: T["audioAnalysisJobId"];
  audioAnalysisLimit: T["audioAnalysisLimit"];
  audioAnalysisOnlyMissing: T["audioAnalysisOnlyMissing"];
  audioAnalysisOverwrite: T["audioAnalysisOverwrite"];
  audioAnalysisProgress: T["audioAnalysisProgress"];
  audioConversionInstallProgress: T["audioConversionInstallProgress"];
  audioConversionJobId: T["audioConversionJobId"];
  audioConversionPreview: T["audioConversionPreview"];
  audioConversionProgress: T["audioConversionProgress"];
  audioConversionRequest: T["audioConversionRequest"];
  audioConversionSetup: T["audioConversionSetup"];
  autoDjAvoidRules: T["autoDjAvoidRules"];
  autoPlayOnTrackChange: T["autoPlayOnTrackChange"];
  autoTagPreview: T["autoTagPreview"];
  autoWriteFetchedLyricsSidecars: T["autoWriteFetchedLyricsSidecars"];
  backendCheckedAt: T["backendCheckedAt"];
  backendLog: T["backendLog"];
  backendMessage: T["backendMessage"];
  backendStatus: T["backendStatus"];
  beginLibraryLoad: T["beginLibraryLoad"];
  buildDesktopScanSnapshot: T["buildDesktopScanSnapshot"];
  bulkUndoBatches: T["bulkUndoBatches"];
  bulkUndoLog: T["bulkUndoLog"];
  bulkUndoRestoreResult: T["bulkUndoRestoreResult"];
  cdAutoLookupMetadata: T["cdAutoLookupMetadata"];
  cdDriveDetected: T["cdDriveDetected"];
  cdPlaybackPrepareChainRef: T["cdPlaybackPrepareChainRef"];
  cdPlaybackPrepareRequestIdRef: T["cdPlaybackPrepareRequestIdRef"];
  cdRipSetup: T["cdRipSetup"];
  checkBackendStatus: T["checkBackendStatus"];
  chromaprintSetup: T["chromaprintSetup"];
  clapBatchSize: T["clapBatchSize"];
  clapCacheDir: T["clapCacheDir"];
  clapInstallProgress: T["clapInstallProgress"];
  clapSamplesPerTrack: T["clapSamplesPerTrack"];
  clapModelId: T["clapModelId"];
  clapNeedsOptionalInstall: T["clapNeedsOptionalInstall"];
  clapStatus: T["clapStatus"];
  clapStatusLoadMessage: T["clapStatusLoadMessage"];
  clapStatusLoadPercent: T["clapStatusLoadPercent"];
  clearFrontendLocalData: T["clearFrontendLocalData"];
  coffeeAnimating: T["coffeeAnimating"];
  commitPlayTrack: T["commitPlayTrack"];
  commitTrackIndexCache: T["commitTrackIndexCache"];
  confirmDeleteTracks: T["confirmDeleteTracks"];
  continuousAutoDjBusy: T["continuousAutoDjBusy"];
  continuousAutoDjEnabled: T["continuousAutoDjEnabled"];
  continuousAutoDjInFlightRef: T["continuousAutoDjInFlightRef"];
  continuousAutoDjSettings: T["continuousAutoDjSettings"];
  currentCdPlaybackDriveId: T["currentCdPlaybackDriveId"];
  currentLibraryTrackQueryKey: T["currentLibraryTrackQueryKey"];
  currentRadioStation: T["currentRadioStation"];
  currentTrack: T["currentTrack"];
  debouncedAdvancedTrackSearch: T["debouncedAdvancedTrackSearch"];
  debouncedSearch: T["debouncedSearch"];
  deletePrompt: T["deletePrompt"];
  detailTrack: T["detailTrack"];
  deviceSyncPreview: T["deviceSyncPreview"];
  dismissQuickStart: T["dismissQuickStart"];
  duplicateActionResult: T["duplicateActionResult"];
  duplicateReview: T["duplicateReview"];
  endLibraryLoad: T["endLibraryLoad"];
  ensureLatestCdPlaybackRequest: T["ensureLatestCdPlaybackRequest"];
  extendContinuousAutoDj: T["extendContinuousAutoDj"];
  externalTrackRequest: T["externalTrackRequest"];
  externalTrackRequestIdRef: T["externalTrackRequestIdRef"];
  fileManagementFocusToolId: T["fileManagementFocusToolId"];
  fileManagementScopeIds: T["fileManagementScopeIds"];
  filenameTagPreview: T["filenameTagPreview"];
  fileOrganizationPreview: T["fileOrganizationPreview"];
  fileOrganizationReport: T["fileOrganizationReport"];
  findTracksByIds: T["findTracksByIds"];
  folderPath: T["folderPath"];
  FolderWatchRefreshTimerRef: T["FolderWatchRefreshTimerRef"];
  folderWatchStatus: T["folderWatchStatus"];
  handleAcknowledgeFolderWatchNotifications: T["handleAcknowledgeFolderWatchNotifications"];
  handleAcoustIdApiKeyChange: T["handleAcoustIdApiKeyChange"];
  handleAddToQueue: T["handleAddToQueue"];
  handleAddTracksToPlaylist: T["handleAddTracksToPlaylist"];
  handleAdvancedTagLibraryChanged: T["handleAdvancedTagLibraryChanged"];
  handleAnalyzeAudio: T["handleAnalyzeAudio"];
  handleAnalyzeTracks: T["handleAnalyzeTracks"];
  handleApplyAutoTag: T["handleApplyAutoTag"];
  handleApplyFilenameTags: T["handleApplyFilenameTags"];
  handleApplyFileOrganization: T["handleApplyFileOrganization"];
  handleApplyFolderWatch: T["handleApplyFolderWatch"];
  handleApplyMetadataCsv: T["handleApplyMetadataCsv"];
  handleApplyTagRegex: T["handleApplyTagRegex"];
  handleAutoWriteFetchedLyricsSidecars: T["handleAutoWriteFetchedLyricsSidecars"];
  handleAvoidAutoDj: T["handleAvoidAutoDj"];
  handleBackupDatabase: T["handleBackupDatabase"];
  handleBrowseAudioConversionTarget: T["handleBrowseAudioConversionTarget"];
  handleBrowseCdRipTarget: T["handleBrowseCdRipTarget"];
  handleBrowseFolder: T["handleBrowseFolder"];
  handleBulkMetadata: T["handleBulkMetadata"];
  handleBulkRating: T["handleBulkRating"];
  handleCancelAudioAnalysis: T["handleCancelAudioAnalysis"];
  handleCancelAudioConversion: T["handleCancelAudioConversion"];
  handleCdAutoLookupMetadata: T["handleCdAutoLookupMetadata"];
  handleChooseMusicFolderAndScan: T["handleChooseMusicFolderAndScan"];
  handleClearArtistCache: T["handleClearArtistCache"];
  handleClearIgnoredDuplicateGroups: T["handleClearIgnoredDuplicateGroups"];
  handleClearLibraryCaches: T["handleClearLibraryCaches"];
  handleClearPlaybackQueue: T["handleClearPlaybackQueue"];
  handleCoffeeClick: T["handleCoffeeClick"];
  handleCommitExternalTrackRequest: T["handleCommitExternalTrackRequest"];
  handleContinuousAutoDjChange: T["handleContinuousAutoDjChange"];
  handleCopySupportBundlePath: T["handleCopySupportBundlePath"];
  handleCreatePlaylist: T["handleCreatePlaylist"];
  handleCreateSupportBundle: T["handleCreateSupportBundle"];
  handleCycleTheme: T["handleCycleTheme"];
  handleDeleteAutoDjAvoidRule: T["handleDeleteAutoDjAvoidRule"];
  handleDeleteInboxAutoReviewRule: T["handleDeleteInboxAutoReviewRule"];
  handleDeletePlaylist: T["handleDeletePlaylist"];
  handleDeleteRecommendationProfile: T["handleDeleteRecommendationProfile"];
  handleDeleteTrack: T["handleDeleteTrack"];
  handleDeleteTracks: T["handleDeleteTracks"];
  handleDeviceSync: T["handleDeviceSync"];
  handleDuplicateAction: T["handleDuplicateAction"];
  handleExportFileOrganizationReport: T["handleExportFileOrganizationReport"];
  handleExportMetadataCsv: T["handleExportMetadataCsv"];
  handleExportMetadataCsvReport: T["handleExportMetadataCsvReport"];
  handleExportPlaylist: T["handleExportPlaylist"];
  handleExportTracks: T["handleExportTracks"];
  handleFetchLyrics: T["handleFetchLyrics"];
  handleIgnoreDuplicateGroup: T["handleIgnoreDuplicateGroup"];
  handleImportPlaylist: T["handleImportPlaylist"];
  handleInstallAudioConversionFfmpeg: T["handleInstallAudioConversionFfmpeg"];
  handleInstallClap: T["handleInstallClap"];
  handleLastFmApiCredentialsChange: T["handleLastFmApiCredentialsChange"];
  handleLibraryAutoTagTracks: T["handleLibraryAutoTagTracks"];
  handleLibraryClapGenreTagTracks: T["handleLibraryClapGenreTagTracks"];
  handleLibraryFingerprintTagTracks: T["handleLibraryFingerprintTagTracks"];
  handleLibraryVolumeTagTracks: T["handleLibraryVolumeTagTracks"];
  handleLoadDuplicateReview: T["handleLoadDuplicateReview"];
  handleMovePlaybackQueueTrack: T["handleMovePlaybackQueueTrack"];
  handleMovePlaylistTrack: T["handleMovePlaylistTrack"];
  handleOpenBackendLog: T["handleOpenBackendLog"];
  handleOpenCurrentAlbumFromPlayer: T["handleOpenCurrentAlbumFromPlayer"];
  handleOpenCurrentArtistFromPlayer: T["handleOpenCurrentArtistFromPlayer"];
  handleOpenCurrentArtistInfoFromPlayer: any;
  handleOpenCurrentTrackFromPlayer: T["handleOpenCurrentTrackFromPlayer"];
  handleOpenDetachedMiniPlayer: T["handleOpenDetachedMiniPlayer"];
  handleOpenExternalUrl: T["handleOpenExternalUrl"];
  handleOpenFileManagementForTracks: T["handleOpenFileManagementForTracks"];
  handleOpenLyricsViewFromPlayer: T["handleOpenLyricsViewFromPlayer"];
  handleOpenOptionalDependencies: T["handleOpenOptionalDependencies"];
  handleOpenQueueViewFromPlayer: T["handleOpenQueueViewFromPlayer"];
  handleOpenSourceFolder: T["handleOpenSourceFolder"];
  handlePauseAudioAnalysis: T["handlePauseAudioAnalysis"];
  handlePlayAlbum: T["handlePlayAlbum"];
  handlePlayArtist: T["handlePlayArtist"];
  handlePlayCdPreviewTrack: T["handlePlayCdPreviewTrack"];
  handlePlayNext: T["handlePlayNext"];
  handlePlayRadioStation: T["handlePlayRadioStation"];
  handlePlayTrack: T["handlePlayTrack"];
  handlePreviewAudioConversion: T["handlePreviewAudioConversion"];
  handlePreviewAutoTag: T["handlePreviewAutoTag"];
  handlePreviewFilenameTags: T["handlePreviewFilenameTags"];
  handlePreviewFileOrganization: T["handlePreviewFileOrganization"];
  handlePreviewMetadataCsv: T["handlePreviewMetadataCsv"];
  handlePreviewTagRegex: T["handlePreviewTagRegex"];
  handleQuickAutoDj: T["handleQuickAutoDj"];
  handleRating: T["handleRating"];
  handleReadReportFile: T["handleReadReportFile"];
  handleRefreshFolderWatch: T["handleRefreshFolderWatch"];
  handleRemoveLibrarySource: T["handleRemoveLibrarySource"];
  handleRemovePlaybackQueueTrack: T["handleRemovePlaybackQueueTrack"];
  handleRemoveTrackFromPlaylist: T["handleRemoveTrackFromPlaylist"];
  handleRemoveTracksFromPlaylist: T["handleRemoveTracksFromPlaylist"];
  handleReorderPlaybackQueueTrack: T["handleReorderPlaybackQueueTrack"];
  handleResetLocalData: T["handleResetLocalData"];
  handleRestartBackend: T["handleRestartBackend"];
  handleRestoreBulkUndoBatch: T["handleRestoreBulkUndoBatch"];
  handleRestoreBulkUndoEntry: T["handleRestoreBulkUndoEntry"];
  handleRestorePlaybackQueue: T["handleRestorePlaybackQueue"];
  handleResumeAudioAnalysis: T["handleResumeAudioAnalysis"];
  handleRevealTrack: T["handleRevealTrack"];
  handleRevealTracksByIds: T["handleRevealTracksByIds"];
  handleReviewInboxTracks: T["handleReviewInboxTracks"];
  handleRunAcousticFingerprintPass: T["handleRunAcousticFingerprintPass"];
  handleSaveAudioConversionSetup: T["handleSaveAudioConversionSetup"];
  handleSaveArtistInfoOverride: T["handleSaveArtistInfoOverride"];
  handleSaveChromaprintSetup: T["handleSaveChromaprintSetup"];
  handleSaveClapConfig: T["handleSaveClapConfig"];
  handleSaveInboxAutoReviewRule: T["handleSaveInboxAutoReviewRule"];
  handleSaveLyrics: T["handleSaveLyrics"];
  handleSavePlaybackQueue: T["handleSavePlaybackQueue"];
  handleSaveRecommendationProfile: T["handleSaveRecommendationProfile"];
  handleSaveTrackMetadata: T["handleSaveTrackMetadata"];
  handleScan: T["handleScan"];
  handleSelectAlbum: T["handleSelectAlbum"];
  handleSelectArtist: T["handleSelectArtist"];
  handleSelectPlaylist: T["handleSelectPlaylist"];
  handleSetDefaultRecommendationProfile: T["handleSetDefaultRecommendationProfile"];
  handleShuffleTracks: T["handleShuffleTracks"];
  handleStartAudioConversion: T["handleStartAudioConversion"];
  handleStartFolderWatch: T["handleStartFolderWatch"];
  handleStopFolderWatch: T["handleStopFolderWatch"];
  handleStopRadioStation: T["handleStopRadioStation"];
  handleSyncFileMetadata: T["handleSyncFileMetadata"];
  handleTrackEnded: T["handleTrackEnded"];
  handleTrackSkipped: T["handleTrackSkipped"];
  handleUndoAction: T["handleUndoAction"];
  handleUndoRecentChange: T["handleUndoRecentChange"];
  handleUpdateInboxNote: T["handleUpdateInboxNote"];
  handleUseSuggestedFolder: T["handleUseSuggestedFolder"];
  handleWriteRatingsToFiles: T["handleWriteRatingsToFiles"];
  hasAdvancedLibraryFilters: T["hasAdvancedLibraryFilters"];
  hasAnalysisIssue: T["hasAnalysisIssue"];
  hasLoadedInitialLibrary: T["hasLoadedInitialLibrary"];
  hasMoreTracks: T["hasMoreTracks"];
  hideFilePaths: T["hideFilePaths"];
  historyEvents: T["historyEvents"];
  historyStats: T["historyStats"];
  importPlaylistPath: T["importPlaylistPath"];
  inbox: T["inbox"];
  isArtistLoading: T["isArtistLoading"];
  isAudioAnalyzing: T["isAudioAnalyzing"];
  isCdPlaybackActive: T["isCdPlaybackActive"];
  isClapInstalling: T["isClapInstalling"];
  isClapStatusLoading: T["isClapStatusLoading"];
  isLibraryLoading: T["isLibraryLoading"];
  isLyricsLoading: T["isLyricsLoading"];
  isScanning: T["isScanning"];
  lastFolderWatchNotificationIdRef: T["lastFolderWatchNotificationIdRef"];
  lastSessionRestoreAttemptedRef: T["lastSessionRestoreAttemptedRef"];
  lastSessionRestoreFinishedRef: T["lastSessionRestoreFinishedRef"];
  lastSessionWriteKeyRef: T["lastSessionWriteKeyRef"];
  libraryAlbumScrollTop: T["libraryAlbumScrollTop"];
  libraryArtistScrollTop: T["libraryArtistScrollTop"];
  libraryCacheQueryKeyRef: T["libraryCacheQueryKeyRef"];
  libraryCompletionScrollTop: T["libraryCompletionScrollTop"];
  libraryFolders: T["libraryFolders"];
  libraryHealth: T["libraryHealth"];
  libraryLoadingCountRef: T["libraryLoadingCountRef"];
  libraryPageRequestsInFlightRef: T["libraryPageRequestsInFlightRef"];
  libraryPlaylistScrollTop: T["libraryPlaylistScrollTop"];
  libraryRequestId: T["libraryRequestId"];
  libraryScrollTop: T["libraryScrollTop"];
  librarySort: T["librarySort"];
  libraryStats: T["libraryStats"];
  libraryTotal: T["libraryTotal"];
  libraryView: T["libraryView"];
  libraryVisibleColumns: T["libraryVisibleColumns"];
  loadAlbums: T["loadAlbums"];
  loadAnalysisClapReadiness: T["loadAnalysisClapReadiness"];
  loadArtistInfo: T["loadArtistInfo"];
  loadArtists: T["loadArtists"];
  loadAudioConversionSetup: T["loadAudioConversionSetup"];
  loadAutoDjAvoidRules: T["loadAutoDjAvoidRules"];
  loadBulkUndoLog: T["loadBulkUndoLog"];
  loadCdRipSetup: T["loadCdRipSetup"];
  loadChromaprintSetup: T["loadChromaprintSetup"];
  loadClapCoverage: T["loadClapCoverage"];
  loadClapStatus: T["loadClapStatus"];
  loadFolderWatchStatus: T["loadFolderWatchStatus"];
  loadHistory: T["loadHistory"];
  loadInbox: T["loadInbox"];
  loadLibraryStats: T["loadLibraryStats"];
  loadMoreTracks: T["loadMoreTracks"];
  loadPlaylists: T["loadPlaylists"];
  loadPriorityLibraryTracks: T["loadPriorityLibraryTracks"];
  loadRecommendationHistory: T["loadRecommendationHistory"];
  loadRecommendationProfiles: T["loadRecommendationProfiles"];
  loadSettings: T["loadSettings"];
  loadStartupDiagnostics: T["loadStartupDiagnostics"];
  loadTracksPage: T["loadTracksPage"];
  loadTrackWindow: T["loadTrackWindow"];
  lyrics: T["lyrics"];
  mergeTrackPage: T["mergeTrackPage"];
  metadataCsvExport: T["metadataCsvExport"];
  metadataCsvImportPreview: T["metadataCsvImportPreview"];
  metadataCsvImportReport: T["metadataCsvImportReport"];
  metadataEditInitialField: T["metadataEditInitialField"];
  metadataEditTrack: T["metadataEditTrack"];
  newPlaylistName: T["newPlaylistName"];
  openApiKeysSettings: T["openApiKeysSettings"];
  openAppContextMenu: T["openAppContextMenu"];
  openMetadataEditor: T["openMetadataEditor"];
  playbackMode: T["playbackMode"];
  playbackQueue: T["playbackQueue"];
  playbackTime: T["playbackTime"];
  playlists: T["playlists"];
  priorityLibraryLoadStartedRef: T["priorityLibraryLoadStartedRef"];
  priorityLibraryQueryKeyRef: T["priorityLibraryQueryKeyRef"];
  queue: T["queue"];
  queueHistory: T["queueHistory"];
  queueUpcomingPlaybackTracks: T["queueUpcomingPlaybackTracks"];
  quickStartDismissed: T["quickStartDismissed"];
  radioPlaybackRequestId: T["radioPlaybackRequestId"];
  recommendationDrift: T["recommendationDrift"];
  recommendationHistory: T["recommendationHistory"];
  recommendationProfiles: T["recommendationProfiles"];
  recordTrackExitQuiet: T["recordTrackExitQuiet"];
  recycleFilesWithDesktop: T["recycleFilesWithDesktop"];
  refreshAnalyzedState: T["refreshAnalyzedState"];
  refreshCdPreviewTrack: T["refreshCdPreviewTrack"];
  refreshTracks: T["refreshTracks"];
  rememberQueueSnapshot: T["rememberQueueSnapshot"];
  rememberRecommendationFeedback: T["rememberRecommendationFeedback"];
  removeTrackEverywhere: T["removeTrackEverywhere"];
  replaceTrackEverywhere: T["replaceTrackEverywhere"];
  replaceUpcomingPlaybackQueue: T["replaceUpcomingPlaybackQueue"];
  reportFile: T["reportFile"];
  requestDeleteTracks: T["requestDeleteTracks"];
  resolveTracksForAction: T["resolveTracksForAction"];
  restoredPlaybackPosition: T["restoredPlaybackPosition"];
  restoreLastPlaybackSession: T["restoreLastPlaybackSession"];
  scanProgress: T["scanProgress"];
  scanResult: T["scanResult"];
  scheduleFolderWatchRefresh: T["scheduleFolderWatchRefresh"];
  search: T["search"];
  selectedAlbumId: T["selectedAlbumId"];
  selectedAlbumTracks: T["selectedAlbumTracks"];
  selectedArtistName: T["selectedArtistName"];
  selectedArtistTracks: T["selectedArtistTracks"];
  selectedPlaylistId: T["selectedPlaylistId"];
  selectedPlaylistTracks: T["selectedPlaylistTracks"];
  setAcousticFingerprintResult: T["setAcousticFingerprintResult"];
  setActivePage: T["setActivePage"];
  setAdvancedTrackSearch: T["setAdvancedTrackSearch"];
  setAlbums: T["setAlbums"];
  setAppContextMenu: T["setAppContextMenu"];
  setArtistInfo: T["setArtistInfo"];
  setArtists: T["setArtists"];
  setArtistTracks: T["setArtistTracks"];
  setAudioAnalysisCoverage: T["setAudioAnalysisCoverage"];
  setAudioAnalysisEligibleTrackTotal: T["setAudioAnalysisEligibleTrackTotal"];
  setAudioAnalysisJobId: T["setAudioAnalysisJobId"];
  setAudioAnalysisLimit: T["setAudioAnalysisLimit"];
  setAudioAnalysisOnlyMissing: T["setAudioAnalysisOnlyMissing"];
  setAudioAnalysisOverwrite: T["setAudioAnalysisOverwrite"];
  setAudioAnalysisProgress: T["setAudioAnalysisProgress"];
  setAudioConversionInstallProgress: T["setAudioConversionInstallProgress"];
  setAudioConversionJobId: T["setAudioConversionJobId"];
  setAudioConversionPreview: T["setAudioConversionPreview"];
  setAudioConversionProgress: T["setAudioConversionProgress"];
  setAudioConversionSetup: T["setAudioConversionSetup"];
  setAutoDjAvoidRules: T["setAutoDjAvoidRules"];
  setAutoPlayOnTrackChange: T["setAutoPlayOnTrackChange"];
  setAutoTagPreview: T["setAutoTagPreview"];
  setAutoWriteFetchedLyricsSidecars: T["setAutoWriteFetchedLyricsSidecars"];
  setBackendCheckedAt: T["setBackendCheckedAt"];
  setBackendLog: T["setBackendLog"];
  setBackendMessage: T["setBackendMessage"];
  setBackendStatus: T["setBackendStatus"];
  setBulkUndoBatches: T["setBulkUndoBatches"];
  setBulkUndoLog: T["setBulkUndoLog"];
  setBulkUndoRestoreResult: T["setBulkUndoRestoreResult"];
  setCdAutoLookupMetadata: T["setCdAutoLookupMetadata"];
  setCdRipSetup: T["setCdRipSetup"];
  setChromaprintSetup: T["setChromaprintSetup"];
  setClapBatchSize: T["setClapBatchSize"];
  setClapCacheDir: T["setClapCacheDir"];
  setClapInstallProgress: T["setClapInstallProgress"];
  setClapSamplesPerTrack: T["setClapSamplesPerTrack"];
  setClapModelId: T["setClapModelId"];
  setClapStatus: T["setClapStatus"];
  setClapStatusLoadMessage: T["setClapStatusLoadMessage"];
  setClapStatusLoadPercent: T["setClapStatusLoadPercent"];
  setCoffeeAnimating: T["setCoffeeAnimating"];
  setContinuousAutoDjBusy: T["setContinuousAutoDjBusy"];
  setContinuousAutoDjEnabled: T["setContinuousAutoDjEnabled"];
  setContinuousAutoDjSettings: T["setContinuousAutoDjSettings"];
  setCurrentRadioStation: T["setCurrentRadioStation"];
  setCurrentTrack: T["setCurrentTrack"];
  setDebouncedAdvancedTrackSearch: T["setDebouncedAdvancedTrackSearch"];
  setDebouncedSearch: T["setDebouncedSearch"];
  setDeletePrompt: T["setDeletePrompt"];
  setDetailTrack: T["setDetailTrack"];
  setDeviceSyncPreview: T["setDeviceSyncPreview"];
  setDuplicateActionResult: T["setDuplicateActionResult"];
  setDuplicateReview: T["setDuplicateReview"];
  setExternalTrackRequest: T["setExternalTrackRequest"];
  setFileManagementFocusToolId: T["setFileManagementFocusToolId"];
  setFileManagementScopeIds: T["setFileManagementScopeIds"];
  setFilenameTagPreview: T["setFilenameTagPreview"];
  setFileOrganizationPreview: T["setFileOrganizationPreview"];
  setFileOrganizationReport: T["setFileOrganizationReport"];
  setFolderPath: T["setFolderPath"];
  setFolderWatchStatus: T["setFolderWatchStatus"];
  setHasLoadedInitialLibrary: T["setHasLoadedInitialLibrary"];
  setHasMoreTracks: T["setHasMoreTracks"];
  setHideFilePaths: T["setHideFilePaths"];
  setHistoryEvents: T["setHistoryEvents"];
  setHistoryStats: T["setHistoryStats"];
  setImportPlaylistPath: T["setImportPlaylistPath"];
  setInbox: T["setInbox"];
  setIsArtistLoading: T["setIsArtistLoading"];
  setIsAudioAnalyzing: T["setIsAudioAnalyzing"];
  setIsClapInstalling: T["setIsClapInstalling"];
  setIsClapStatusLoading: T["setIsClapStatusLoading"];
  setIsLibraryLoading: T["setIsLibraryLoading"];
  setIsLyricsLoading: T["setIsLyricsLoading"];
  setIsScanning: T["setIsScanning"];
  setLibraryAlbumScrollTop: T["setLibraryAlbumScrollTop"];
  setLibraryArtistScrollTop: T["setLibraryArtistScrollTop"];
  setLibraryCompletionScrollTop: T["setLibraryCompletionScrollTop"];
  setLibraryFolders: T["setLibraryFolders"];
  setLibraryHealth: T["setLibraryHealth"];
  setLibraryPlaylistScrollTop: T["setLibraryPlaylistScrollTop"];
  setLibraryScrollTop: T["setLibraryScrollTop"];
  setLibrarySort: T["setLibrarySort"];
  setLibraryStats: T["setLibraryStats"];
  setLibraryTotal: T["setLibraryTotal"];
  setLibraryView: T["setLibraryView"];
  setLibraryVisibleColumns: T["setLibraryVisibleColumns"];
  setLyrics: T["setLyrics"];
  setMetadataCsvExport: T["setMetadataCsvExport"];
  setMetadataCsvImportPreview: T["setMetadataCsvImportPreview"];
  setMetadataCsvImportReport: T["setMetadataCsvImportReport"];
  setMetadataEditInitialField: T["setMetadataEditInitialField"];
  setMetadataEditTrack: T["setMetadataEditTrack"];
  setNewPlaylistName: T["setNewPlaylistName"];
  setPlaybackMode: T["setPlaybackMode"];
  setPlaybackQueue: T["setPlaybackQueue"];
  setPlaybackTime: T["setPlaybackTime"];
  setPlaylists: T["setPlaylists"];
  setQueue: T["setQueue"];
  setQueueHistory: T["setQueueHistory"];
  setQuickStartDismissed: T["setQuickStartDismissed"];
  setRadioPlaybackRequestId: T["setRadioPlaybackRequestId"];
  setRecommendationDrift: T["setRecommendationDrift"];
  setRecommendationHistory: T["setRecommendationHistory"];
  setRecommendationProfiles: T["setRecommendationProfiles"];
  setReportFile: T["setReportFile"];
  setRestoredPlaybackPosition: T["setRestoredPlaybackPosition"];
  setScanProgress: T["setScanProgress"];
  setScanResult: T["setScanResult"];
  setSearch: T["setSearch"];
  setSelectedAlbumId: T["setSelectedAlbumId"];
  setSelectedAlbumTracks: T["setSelectedAlbumTracks"];
  setSelectedArtistName: T["setSelectedArtistName"];
  setSelectedArtistTracks: T["setSelectedArtistTracks"];
  setSelectedPlaylistId: T["setSelectedPlaylistId"];
  setSelectedPlaylistTracks: T["setSelectedPlaylistTracks"];
  setSettings: T["setSettings"];
  setSettingsFocusSection: T["setSettingsFocusSection"];
  setStartupDiagnostics: T["setStartupDiagnostics"];
  setStatus: T["setStatus"];
  setSupportBundlePath: T["setSupportBundlePath"];
  setTagRegexPreview: T["setTagRegexPreview"];
  setTargetPlaylistId: T["setTargetPlaylistId"];
  settings: T["settings"];
  settingsFocusSection: T["settingsFocusSection"];
  setTrackIndexCache: T["setTrackIndexCache"];
  setTracks: T["setTracks"];
  setUiPreferences: T["setUiPreferences"];
  setUndoAction: T["setUndoAction"];
  setWriteRatingsToFiles: T["setWriteRatingsToFiles"];
  showCdPage: T["showCdPage"];
  showUndoAction: T["showUndoAction"];
  startupBackgroundHydratedRef: T["startupBackgroundHydratedRef"];
  startupDiagnostics: T["startupDiagnostics"];
  startupLibrarySnapshot: T["startupLibrarySnapshot"];
  status: T["status"];
  supportBundlePath: T["supportBundlePath"];
  tagRegexPreview: T["tagRegexPreview"];
  targetPlaylistId: T["targetPlaylistId"];
  trackIndexCache: T["trackIndexCache"];
  trackIndexCacheRef: T["trackIndexCacheRef"];
  tracks: T["tracks"];
  uiPreferences: T["uiPreferences"];
  undoAction: T["undoAction"];
  undoTimerRef: T["undoTimerRef"];
  updateCachedTracks: T["updateCachedTracks"];
  validateMusicFoldersWithDesktop: T["validateMusicFoldersWithDesktop"];
  waitForBackendStartup: T["waitForBackendStartup"];
  writeRatingsToFiles: T["writeRatingsToFiles"];
} {
  return {
      acousticFingerprintResult: model.acousticFingerprintResult,
      activePage: model.activePage,
      advancedTrackSearch: model.advancedTrackSearch,
      albums: model.albums,
      appContextMenu: model.appContextMenu,
      applyClapStatus: model.applyClapStatus,
      applyFolderWatchResponse: model.applyFolderWatchResponse,
      applyFolderWatchStatus: model.applyFolderWatchStatus,
      artistInfo: model.artistInfo,
      artists: model.artists,
      artistTracks: model.artistTracks,
      audioAnalysisCoverage: model.audioAnalysisCoverage,
      audioAnalysisEligibleTrackTotal: model.audioAnalysisEligibleTrackTotal,
      audioAnalysisJobId: model.audioAnalysisJobId,
      audioAnalysisLimit: model.audioAnalysisLimit,
      audioAnalysisOnlyMissing: model.audioAnalysisOnlyMissing,
      audioAnalysisOverwrite: model.audioAnalysisOverwrite,
      audioAnalysisProgress: model.audioAnalysisProgress,
      audioConversionInstallProgress: model.audioConversionInstallProgress,
      audioConversionJobId: model.audioConversionJobId,
      audioConversionPreview: model.audioConversionPreview,
      audioConversionProgress: model.audioConversionProgress,
      audioConversionRequest: model.audioConversionRequest,
      audioConversionSetup: model.audioConversionSetup,
      autoDjAvoidRules: model.autoDjAvoidRules,
      autoPlayOnTrackChange: model.autoPlayOnTrackChange,
      autoTagPreview: model.autoTagPreview,
      autoWriteFetchedLyricsSidecars: model.autoWriteFetchedLyricsSidecars,
      backendCheckedAt: model.backendCheckedAt,
      backendLog: model.backendLog,
      backendMessage: model.backendMessage,
      backendStatus: model.backendStatus,
      beginLibraryLoad: model.beginLibraryLoad,
      buildDesktopScanSnapshot: model.buildDesktopScanSnapshot,
      bulkUndoBatches: model.bulkUndoBatches,
      bulkUndoLog: model.bulkUndoLog,
      bulkUndoRestoreResult: model.bulkUndoRestoreResult,
      cdAutoLookupMetadata: model.cdAutoLookupMetadata,
      cdDriveDetected: model.cdDriveDetected,
      cdPlaybackPrepareChainRef: model.cdPlaybackPrepareChainRef,
      cdPlaybackPrepareRequestIdRef: model.cdPlaybackPrepareRequestIdRef,
      cdRipSetup: model.cdRipSetup,
      checkBackendStatus: model.checkBackendStatus,
      chromaprintSetup: model.chromaprintSetup,
      clapBatchSize: model.clapBatchSize,
      clapCacheDir: model.clapCacheDir,
      clapInstallProgress: model.clapInstallProgress,
      clapSamplesPerTrack: model.clapSamplesPerTrack,
      clapModelId: model.clapModelId,
      clapNeedsOptionalInstall: model.clapNeedsOptionalInstall,
      clapStatus: model.clapStatus,
      clapStatusLoadMessage: model.clapStatusLoadMessage,
      clapStatusLoadPercent: model.clapStatusLoadPercent,
      clearFrontendLocalData: model.clearFrontendLocalData,
      coffeeAnimating: model.coffeeAnimating,
      commitPlayTrack: model.commitPlayTrack,
      commitTrackIndexCache: model.commitTrackIndexCache,
      confirmDeleteTracks: model.confirmDeleteTracks,
      continuousAutoDjBusy: model.continuousAutoDjBusy,
      continuousAutoDjEnabled: model.continuousAutoDjEnabled,
      continuousAutoDjInFlightRef: model.continuousAutoDjInFlightRef,
      continuousAutoDjSettings: model.continuousAutoDjSettings,
      currentCdPlaybackDriveId: model.currentCdPlaybackDriveId,
      currentLibraryTrackQueryKey: model.currentLibraryTrackQueryKey,
      currentRadioStation: model.currentRadioStation,
      currentTrack: model.currentTrack,
      debouncedAdvancedTrackSearch: model.debouncedAdvancedTrackSearch,
      debouncedSearch: model.debouncedSearch,
      deletePrompt: model.deletePrompt,
      detailTrack: model.detailTrack,
      deviceSyncPreview: model.deviceSyncPreview,
      dismissQuickStart: model.dismissQuickStart,
      duplicateActionResult: model.duplicateActionResult,
      duplicateReview: model.duplicateReview,
      endLibraryLoad: model.endLibraryLoad,
      ensureLatestCdPlaybackRequest: model.ensureLatestCdPlaybackRequest,
      extendContinuousAutoDj: model.extendContinuousAutoDj,
      externalTrackRequest: model.externalTrackRequest,
      externalTrackRequestIdRef: model.externalTrackRequestIdRef,
      fileManagementFocusToolId: model.fileManagementFocusToolId,
      fileManagementScopeIds: model.fileManagementScopeIds,
      filenameTagPreview: model.filenameTagPreview,
      fileOrganizationPreview: model.fileOrganizationPreview,
      fileOrganizationReport: model.fileOrganizationReport,
      findTracksByIds: model.findTracksByIds,
      folderPath: model.folderPath,
      FolderWatchRefreshTimerRef: model.FolderWatchRefreshTimerRef,
      folderWatchStatus: model.folderWatchStatus,
      handleAcknowledgeFolderWatchNotifications: model.handleAcknowledgeFolderWatchNotifications,
      handleAcoustIdApiKeyChange: model.handleAcoustIdApiKeyChange,
      handleAddToQueue: model.handleAddToQueue,
      handleAddTracksToPlaylist: model.handleAddTracksToPlaylist,
      handleAdvancedTagLibraryChanged: model.handleAdvancedTagLibraryChanged,
      handleAnalyzeAudio: model.handleAnalyzeAudio,
      handleAnalyzeTracks: model.handleAnalyzeTracks,
      handleApplyAutoTag: model.handleApplyAutoTag,
      handleApplyFilenameTags: model.handleApplyFilenameTags,
      handleApplyFileOrganization: model.handleApplyFileOrganization,
      handleApplyFolderWatch: model.handleApplyFolderWatch,
      handleApplyMetadataCsv: model.handleApplyMetadataCsv,
      handleApplyTagRegex: model.handleApplyTagRegex,
      handleAutoWriteFetchedLyricsSidecars: model.handleAutoWriteFetchedLyricsSidecars,
      handleAvoidAutoDj: model.handleAvoidAutoDj,
      handleBackupDatabase: model.handleBackupDatabase,
      handleBrowseAudioConversionTarget: model.handleBrowseAudioConversionTarget,
      handleBrowseCdRipTarget: model.handleBrowseCdRipTarget,
      handleBrowseFolder: model.handleBrowseFolder,
      handleBulkMetadata: model.handleBulkMetadata,
      handleBulkRating: model.handleBulkRating,
      handleCancelAudioAnalysis: model.handleCancelAudioAnalysis,
      handleCancelAudioConversion: model.handleCancelAudioConversion,
      handleCdAutoLookupMetadata: model.handleCdAutoLookupMetadata,
      handleChooseMusicFolderAndScan: model.handleChooseMusicFolderAndScan,
      handleClearArtistCache: model.handleClearArtistCache,
      handleClearIgnoredDuplicateGroups: model.handleClearIgnoredDuplicateGroups,
      handleClearLibraryCaches: model.handleClearLibraryCaches,
      handleClearPlaybackQueue: model.handleClearPlaybackQueue,
      handleCoffeeClick: model.handleCoffeeClick,
      handleCommitExternalTrackRequest: model.handleCommitExternalTrackRequest,
      handleContinuousAutoDjChange: model.handleContinuousAutoDjChange,
      handleCopySupportBundlePath: model.handleCopySupportBundlePath,
      handleCreatePlaylist: model.handleCreatePlaylist,
      handleCreateSupportBundle: model.handleCreateSupportBundle,
      handleCycleTheme: model.handleCycleTheme,
      handleDeleteAutoDjAvoidRule: model.handleDeleteAutoDjAvoidRule,
      handleDeleteInboxAutoReviewRule: model.handleDeleteInboxAutoReviewRule,
      handleDeletePlaylist: model.handleDeletePlaylist,
      handleDeleteRecommendationProfile: model.handleDeleteRecommendationProfile,
      handleDeleteTrack: model.handleDeleteTrack,
      handleDeleteTracks: model.handleDeleteTracks,
      handleDeviceSync: model.handleDeviceSync,
      handleDuplicateAction: model.handleDuplicateAction,
      handleExportFileOrganizationReport: model.handleExportFileOrganizationReport,
      handleExportMetadataCsv: model.handleExportMetadataCsv,
      handleExportMetadataCsvReport: model.handleExportMetadataCsvReport,
      handleExportPlaylist: model.handleExportPlaylist,
      handleExportTracks: model.handleExportTracks,
      handleFetchLyrics: model.handleFetchLyrics,
      handleIgnoreDuplicateGroup: model.handleIgnoreDuplicateGroup,
      handleImportPlaylist: model.handleImportPlaylist,
      handleInstallAudioConversionFfmpeg: model.handleInstallAudioConversionFfmpeg,
      handleInstallClap: model.handleInstallClap,
      handleLastFmApiCredentialsChange: model.handleLastFmApiCredentialsChange,
      handleLibraryAutoTagTracks: model.handleLibraryAutoTagTracks,
      handleLibraryClapGenreTagTracks: model.handleLibraryClapGenreTagTracks,
      handleLibraryFingerprintTagTracks: model.handleLibraryFingerprintTagTracks,
      handleLibraryVolumeTagTracks: model.handleLibraryVolumeTagTracks,
      handleLoadDuplicateReview: model.handleLoadDuplicateReview,
      handleMovePlaybackQueueTrack: model.handleMovePlaybackQueueTrack,
      handleMovePlaylistTrack: model.handleMovePlaylistTrack,
      handleOpenBackendLog: model.handleOpenBackendLog,
      handleOpenCurrentAlbumFromPlayer: model.handleOpenCurrentAlbumFromPlayer,
      handleOpenCurrentArtistFromPlayer: model.handleOpenCurrentArtistFromPlayer,
      handleOpenCurrentArtistInfoFromPlayer: (model as any).handleOpenCurrentArtistInfoFromPlayer,
      handleOpenCurrentTrackFromPlayer: model.handleOpenCurrentTrackFromPlayer,
      handleOpenDetachedMiniPlayer: model.handleOpenDetachedMiniPlayer,
      handleOpenExternalUrl: model.handleOpenExternalUrl,
      handleOpenFileManagementForTracks: model.handleOpenFileManagementForTracks,
      handleOpenLyricsViewFromPlayer: model.handleOpenLyricsViewFromPlayer,
      handleOpenOptionalDependencies: model.handleOpenOptionalDependencies,
      handleOpenQueueViewFromPlayer: model.handleOpenQueueViewFromPlayer,
      handleOpenSourceFolder: model.handleOpenSourceFolder,
      handlePauseAudioAnalysis: model.handlePauseAudioAnalysis,
      handlePlayAlbum: model.handlePlayAlbum,
      handlePlayArtist: model.handlePlayArtist,
      handlePlayCdPreviewTrack: model.handlePlayCdPreviewTrack,
      handlePlayNext: model.handlePlayNext,
      handlePlayRadioStation: model.handlePlayRadioStation,
      handlePlayTrack: model.handlePlayTrack,
      handlePreviewAudioConversion: model.handlePreviewAudioConversion,
      handlePreviewAutoTag: model.handlePreviewAutoTag,
      handlePreviewFilenameTags: model.handlePreviewFilenameTags,
      handlePreviewFileOrganization: model.handlePreviewFileOrganization,
      handlePreviewMetadataCsv: model.handlePreviewMetadataCsv,
      handlePreviewTagRegex: model.handlePreviewTagRegex,
      handleQuickAutoDj: model.handleQuickAutoDj,
      handleRating: model.handleRating,
      handleReadReportFile: model.handleReadReportFile,
      handleRefreshFolderWatch: model.handleRefreshFolderWatch,
      handleRemoveLibrarySource: model.handleRemoveLibrarySource,
      handleRemovePlaybackQueueTrack: model.handleRemovePlaybackQueueTrack,
      handleRemoveTrackFromPlaylist: model.handleRemoveTrackFromPlaylist,
      handleRemoveTracksFromPlaylist: model.handleRemoveTracksFromPlaylist,
      handleReorderPlaybackQueueTrack: model.handleReorderPlaybackQueueTrack,
      handleResetLocalData: model.handleResetLocalData,
      handleRestartBackend: model.handleRestartBackend,
      handleRestoreBulkUndoBatch: model.handleRestoreBulkUndoBatch,
      handleRestoreBulkUndoEntry: model.handleRestoreBulkUndoEntry,
      handleRestorePlaybackQueue: model.handleRestorePlaybackQueue,
      handleResumeAudioAnalysis: model.handleResumeAudioAnalysis,
      handleRevealTrack: model.handleRevealTrack,
      handleRevealTracksByIds: model.handleRevealTracksByIds,
      handleReviewInboxTracks: model.handleReviewInboxTracks,
      handleRunAcousticFingerprintPass: model.handleRunAcousticFingerprintPass,
      handleSaveAudioConversionSetup: model.handleSaveAudioConversionSetup,
      handleSaveArtistInfoOverride: model.handleSaveArtistInfoOverride,
      handleSaveChromaprintSetup: model.handleSaveChromaprintSetup,
      handleSaveClapConfig: model.handleSaveClapConfig,
      handleSaveInboxAutoReviewRule: model.handleSaveInboxAutoReviewRule,
      handleSaveLyrics: model.handleSaveLyrics,
      handleSavePlaybackQueue: model.handleSavePlaybackQueue,
      handleSaveRecommendationProfile: model.handleSaveRecommendationProfile,
      handleSaveTrackMetadata: model.handleSaveTrackMetadata,
      handleScan: model.handleScan,
      handleSelectAlbum: model.handleSelectAlbum,
      handleSelectArtist: model.handleSelectArtist,
      handleSelectPlaylist: model.handleSelectPlaylist,
      handleSetDefaultRecommendationProfile: model.handleSetDefaultRecommendationProfile,
      handleShuffleTracks: model.handleShuffleTracks,
      handleStartAudioConversion: model.handleStartAudioConversion,
      handleStartFolderWatch: model.handleStartFolderWatch,
      handleStopFolderWatch: model.handleStopFolderWatch,
      handleStopRadioStation: model.handleStopRadioStation,
      handleSyncFileMetadata: model.handleSyncFileMetadata,
      handleTrackEnded: model.handleTrackEnded,
      handleTrackSkipped: model.handleTrackSkipped,
      handleUndoAction: model.handleUndoAction,
      handleUndoRecentChange: model.handleUndoRecentChange,
      handleUpdateInboxNote: model.handleUpdateInboxNote,
      handleUseSuggestedFolder: model.handleUseSuggestedFolder,
      handleWriteRatingsToFiles: model.handleWriteRatingsToFiles,
      hasAdvancedLibraryFilters: model.hasAdvancedLibraryFilters,
      hasAnalysisIssue: model.hasAnalysisIssue,
      hasLoadedInitialLibrary: model.hasLoadedInitialLibrary,
      hasMoreTracks: model.hasMoreTracks,
      hideFilePaths: model.hideFilePaths,
      historyEvents: model.historyEvents,
      historyStats: model.historyStats,
      importPlaylistPath: model.importPlaylistPath,
      inbox: model.inbox,
      isArtistLoading: model.isArtistLoading,
      isAudioAnalyzing: model.isAudioAnalyzing,
      isCdPlaybackActive: model.isCdPlaybackActive,
      isClapInstalling: model.isClapInstalling,
      isClapStatusLoading: model.isClapStatusLoading,
      isLibraryLoading: model.isLibraryLoading,
      isLyricsLoading: model.isLyricsLoading,
      isScanning: model.isScanning,
      lastFolderWatchNotificationIdRef: model.lastFolderWatchNotificationIdRef,
      lastSessionRestoreAttemptedRef: model.lastSessionRestoreAttemptedRef,
      lastSessionRestoreFinishedRef: model.lastSessionRestoreFinishedRef,
      lastSessionWriteKeyRef: model.lastSessionWriteKeyRef,
      libraryAlbumScrollTop: model.libraryAlbumScrollTop,
      libraryArtistScrollTop: model.libraryArtistScrollTop,
      libraryCacheQueryKeyRef: model.libraryCacheQueryKeyRef,
      libraryCompletionScrollTop: model.libraryCompletionScrollTop,
      libraryFolders: model.libraryFolders,
      libraryHealth: model.libraryHealth,
      libraryLoadingCountRef: model.libraryLoadingCountRef,
      libraryPageRequestsInFlightRef: model.libraryPageRequestsInFlightRef,
      libraryPlaylistScrollTop: model.libraryPlaylistScrollTop,
      libraryRequestId: model.libraryRequestId,
      libraryScrollTop: model.libraryScrollTop,
      librarySort: model.librarySort,
      libraryStats: model.libraryStats,
      libraryTotal: model.libraryTotal,
      libraryView: model.libraryView,
      libraryVisibleColumns: model.libraryVisibleColumns,
      loadAlbums: model.loadAlbums,
      loadAnalysisClapReadiness: model.loadAnalysisClapReadiness,
      loadArtistInfo: model.loadArtistInfo,
      loadArtists: model.loadArtists,
      loadAudioConversionSetup: model.loadAudioConversionSetup,
      loadAutoDjAvoidRules: model.loadAutoDjAvoidRules,
      loadBulkUndoLog: model.loadBulkUndoLog,
      loadCdRipSetup: model.loadCdRipSetup,
      loadChromaprintSetup: model.loadChromaprintSetup,
      loadClapCoverage: model.loadClapCoverage,
      loadClapStatus: model.loadClapStatus,
      loadFolderWatchStatus: model.loadFolderWatchStatus,
      loadHistory: model.loadHistory,
      loadInbox: model.loadInbox,
      loadLibraryStats: model.loadLibraryStats,
      loadMoreTracks: model.loadMoreTracks,
      loadPlaylists: model.loadPlaylists,
      loadPriorityLibraryTracks: model.loadPriorityLibraryTracks,
      loadRecommendationHistory: model.loadRecommendationHistory,
      loadRecommendationProfiles: model.loadRecommendationProfiles,
      loadSettings: model.loadSettings,
      loadStartupDiagnostics: model.loadStartupDiagnostics,
      loadTracksPage: model.loadTracksPage,
      loadTrackWindow: model.loadTrackWindow,
      lyrics: model.lyrics,
      mergeTrackPage: model.mergeTrackPage,
      metadataCsvExport: model.metadataCsvExport,
      metadataCsvImportPreview: model.metadataCsvImportPreview,
      metadataCsvImportReport: model.metadataCsvImportReport,
      metadataEditInitialField: model.metadataEditInitialField,
      metadataEditTrack: model.metadataEditTrack,
      newPlaylistName: model.newPlaylistName,
      openApiKeysSettings: model.openApiKeysSettings,
      openAppContextMenu: model.openAppContextMenu,
      openMetadataEditor: model.openMetadataEditor,
      playbackMode: model.playbackMode,
      playbackQueue: model.playbackQueue,
      playbackTime: model.playbackTime,
      playlists: model.playlists,
      priorityLibraryLoadStartedRef: model.priorityLibraryLoadStartedRef,
      priorityLibraryQueryKeyRef: model.priorityLibraryQueryKeyRef,
      queue: model.queue,
      queueHistory: model.queueHistory,
      queueUpcomingPlaybackTracks: model.queueUpcomingPlaybackTracks,
      quickStartDismissed: model.quickStartDismissed,
      radioPlaybackRequestId: model.radioPlaybackRequestId,
      recommendationDrift: model.recommendationDrift,
      recommendationHistory: model.recommendationHistory,
      recommendationProfiles: model.recommendationProfiles,
      recordTrackExitQuiet: model.recordTrackExitQuiet,
      recycleFilesWithDesktop: model.recycleFilesWithDesktop,
      refreshAnalyzedState: model.refreshAnalyzedState,
      refreshCdPreviewTrack: model.refreshCdPreviewTrack,
      refreshTracks: model.refreshTracks,
      rememberQueueSnapshot: model.rememberQueueSnapshot,
      rememberRecommendationFeedback: model.rememberRecommendationFeedback,
      removeTrackEverywhere: model.removeTrackEverywhere,
      replaceTrackEverywhere: model.replaceTrackEverywhere,
      replaceUpcomingPlaybackQueue: model.replaceUpcomingPlaybackQueue,
      reportFile: model.reportFile,
      requestDeleteTracks: model.requestDeleteTracks,
      resolveTracksForAction: model.resolveTracksForAction,
      restoredPlaybackPosition: model.restoredPlaybackPosition,
      restoreLastPlaybackSession: model.restoreLastPlaybackSession,
      scanProgress: model.scanProgress,
      scanResult: model.scanResult,
      scheduleFolderWatchRefresh: model.scheduleFolderWatchRefresh,
      search: model.search,
      selectedAlbumId: model.selectedAlbumId,
      selectedAlbumTracks: model.selectedAlbumTracks,
      selectedArtistName: model.selectedArtistName,
      selectedArtistTracks: model.selectedArtistTracks,
      selectedPlaylistId: model.selectedPlaylistId,
      selectedPlaylistTracks: model.selectedPlaylistTracks,
      setAcousticFingerprintResult: model.setAcousticFingerprintResult,
      setActivePage: model.setActivePage,
      setAdvancedTrackSearch: model.setAdvancedTrackSearch,
      setAlbums: model.setAlbums,
      setAppContextMenu: model.setAppContextMenu,
      setArtistInfo: model.setArtistInfo,
      setArtists: model.setArtists,
      setArtistTracks: model.setArtistTracks,
      setAudioAnalysisCoverage: model.setAudioAnalysisCoverage,
      setAudioAnalysisEligibleTrackTotal: model.setAudioAnalysisEligibleTrackTotal,
      setAudioAnalysisJobId: model.setAudioAnalysisJobId,
      setAudioAnalysisLimit: model.setAudioAnalysisLimit,
      setAudioAnalysisOnlyMissing: model.setAudioAnalysisOnlyMissing,
      setAudioAnalysisOverwrite: model.setAudioAnalysisOverwrite,
      setAudioAnalysisProgress: model.setAudioAnalysisProgress,
      setAudioConversionInstallProgress: model.setAudioConversionInstallProgress,
      setAudioConversionJobId: model.setAudioConversionJobId,
      setAudioConversionPreview: model.setAudioConversionPreview,
      setAudioConversionProgress: model.setAudioConversionProgress,
      setAudioConversionSetup: model.setAudioConversionSetup,
      setAutoDjAvoidRules: model.setAutoDjAvoidRules,
      setAutoPlayOnTrackChange: model.setAutoPlayOnTrackChange,
      setAutoTagPreview: model.setAutoTagPreview,
      setAutoWriteFetchedLyricsSidecars: model.setAutoWriteFetchedLyricsSidecars,
      setBackendCheckedAt: model.setBackendCheckedAt,
      setBackendLog: model.setBackendLog,
      setBackendMessage: model.setBackendMessage,
      setBackendStatus: model.setBackendStatus,
      setBulkUndoBatches: model.setBulkUndoBatches,
      setBulkUndoLog: model.setBulkUndoLog,
      setBulkUndoRestoreResult: model.setBulkUndoRestoreResult,
      setCdAutoLookupMetadata: model.setCdAutoLookupMetadata,
      setCdRipSetup: model.setCdRipSetup,
      setChromaprintSetup: model.setChromaprintSetup,
      setClapBatchSize: model.setClapBatchSize,
      setClapCacheDir: model.setClapCacheDir,
      setClapInstallProgress: model.setClapInstallProgress,
      setClapSamplesPerTrack: model.setClapSamplesPerTrack,
      setClapModelId: model.setClapModelId,
      setClapStatus: model.setClapStatus,
      setClapStatusLoadMessage: model.setClapStatusLoadMessage,
      setClapStatusLoadPercent: model.setClapStatusLoadPercent,
      setCoffeeAnimating: model.setCoffeeAnimating,
      setContinuousAutoDjBusy: model.setContinuousAutoDjBusy,
      setContinuousAutoDjEnabled: model.setContinuousAutoDjEnabled,
      setContinuousAutoDjSettings: model.setContinuousAutoDjSettings,
      setCurrentRadioStation: model.setCurrentRadioStation,
      setCurrentTrack: model.setCurrentTrack,
      setDebouncedAdvancedTrackSearch: model.setDebouncedAdvancedTrackSearch,
      setDebouncedSearch: model.setDebouncedSearch,
      setDeletePrompt: model.setDeletePrompt,
      setDetailTrack: model.setDetailTrack,
      setDeviceSyncPreview: model.setDeviceSyncPreview,
      setDuplicateActionResult: model.setDuplicateActionResult,
      setDuplicateReview: model.setDuplicateReview,
      setExternalTrackRequest: model.setExternalTrackRequest,
      setFileManagementFocusToolId: model.setFileManagementFocusToolId,
      setFileManagementScopeIds: model.setFileManagementScopeIds,
      setFilenameTagPreview: model.setFilenameTagPreview,
      setFileOrganizationPreview: model.setFileOrganizationPreview,
      setFileOrganizationReport: model.setFileOrganizationReport,
      setFolderPath: model.setFolderPath,
      setFolderWatchStatus: model.setFolderWatchStatus,
      setHasLoadedInitialLibrary: model.setHasLoadedInitialLibrary,
      setHasMoreTracks: model.setHasMoreTracks,
      setHideFilePaths: model.setHideFilePaths,
      setHistoryEvents: model.setHistoryEvents,
      setHistoryStats: model.setHistoryStats,
      setImportPlaylistPath: model.setImportPlaylistPath,
      setInbox: model.setInbox,
      setIsArtistLoading: model.setIsArtistLoading,
      setIsAudioAnalyzing: model.setIsAudioAnalyzing,
      setIsClapInstalling: model.setIsClapInstalling,
      setIsClapStatusLoading: model.setIsClapStatusLoading,
      setIsLibraryLoading: model.setIsLibraryLoading,
      setIsLyricsLoading: model.setIsLyricsLoading,
      setIsScanning: model.setIsScanning,
      setLibraryAlbumScrollTop: model.setLibraryAlbumScrollTop,
      setLibraryArtistScrollTop: model.setLibraryArtistScrollTop,
      setLibraryCompletionScrollTop: model.setLibraryCompletionScrollTop,
      setLibraryFolders: model.setLibraryFolders,
      setLibraryHealth: model.setLibraryHealth,
      setLibraryPlaylistScrollTop: model.setLibraryPlaylistScrollTop,
      setLibraryScrollTop: model.setLibraryScrollTop,
      setLibrarySort: model.setLibrarySort,
      setLibraryStats: model.setLibraryStats,
      setLibraryTotal: model.setLibraryTotal,
      setLibraryView: model.setLibraryView,
      setLibraryVisibleColumns: model.setLibraryVisibleColumns,
      setLyrics: model.setLyrics,
      setMetadataCsvExport: model.setMetadataCsvExport,
      setMetadataCsvImportPreview: model.setMetadataCsvImportPreview,
      setMetadataCsvImportReport: model.setMetadataCsvImportReport,
      setMetadataEditInitialField: model.setMetadataEditInitialField,
      setMetadataEditTrack: model.setMetadataEditTrack,
      setNewPlaylistName: model.setNewPlaylistName,
      setPlaybackMode: model.setPlaybackMode,
      setPlaybackQueue: model.setPlaybackQueue,
      setPlaybackTime: model.setPlaybackTime,
      setPlaylists: model.setPlaylists,
      setQueue: model.setQueue,
      setQueueHistory: model.setQueueHistory,
      setQuickStartDismissed: model.setQuickStartDismissed,
      setRadioPlaybackRequestId: model.setRadioPlaybackRequestId,
      setRecommendationDrift: model.setRecommendationDrift,
      setRecommendationHistory: model.setRecommendationHistory,
      setRecommendationProfiles: model.setRecommendationProfiles,
      setReportFile: model.setReportFile,
      setRestoredPlaybackPosition: model.setRestoredPlaybackPosition,
      setScanProgress: model.setScanProgress,
      setScanResult: model.setScanResult,
      setSearch: model.setSearch,
      setSelectedAlbumId: model.setSelectedAlbumId,
      setSelectedAlbumTracks: model.setSelectedAlbumTracks,
      setSelectedArtistName: model.setSelectedArtistName,
      setSelectedArtistTracks: model.setSelectedArtistTracks,
      setSelectedPlaylistId: model.setSelectedPlaylistId,
      setSelectedPlaylistTracks: model.setSelectedPlaylistTracks,
      setSettings: model.setSettings,
      setSettingsFocusSection: model.setSettingsFocusSection,
      setStartupDiagnostics: model.setStartupDiagnostics,
      setStatus: model.setStatus,
      setSupportBundlePath: model.setSupportBundlePath,
      setTagRegexPreview: model.setTagRegexPreview,
      setTargetPlaylistId: model.setTargetPlaylistId,
      settings: model.settings,
      settingsFocusSection: model.settingsFocusSection,
      setTrackIndexCache: model.setTrackIndexCache,
      setTracks: model.setTracks,
      setUiPreferences: model.setUiPreferences,
      setUndoAction: model.setUndoAction,
      setWriteRatingsToFiles: model.setWriteRatingsToFiles,
      showCdPage: model.showCdPage,
      showUndoAction: model.showUndoAction,
      startupBackgroundHydratedRef: model.startupBackgroundHydratedRef,
      startupDiagnostics: model.startupDiagnostics,
      startupLibrarySnapshot: model.startupLibrarySnapshot,
      status: model.status,
      supportBundlePath: model.supportBundlePath,
      tagRegexPreview: model.tagRegexPreview,
      targetPlaylistId: model.targetPlaylistId,
      trackIndexCache: model.trackIndexCache,
      trackIndexCacheRef: model.trackIndexCacheRef,
      tracks: model.tracks,
      uiPreferences: model.uiPreferences,
      undoAction: model.undoAction,
      undoTimerRef: model.undoTimerRef,
      updateCachedTracks: model.updateCachedTracks,
      validateMusicFoldersWithDesktop: model.validateMusicFoldersWithDesktop,
      waitForBackendStartup: model.waitForBackendStartup,
      writeRatingsToFiles: model.writeRatingsToFiles,
    };
}
